version: "3.9"
services:
  agent-shard-1: 
    image: postgres:latest
    volumes:
      - ~./db-data-1:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  agent-shard-2: 
    image: postgres:latest
    volumes:
      - ~./db-data-2:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5433
    command: -p 5433
  # flyway:
  #   build: .
  #   command: /bin/bash -c "echo 'HELLO'"
  #   volumes:
  #     - ./sql:/flyway/sql
  #     - ./conf:/flyway/conf
  #   depends_on:
  #     - agent-shard-1
  #     - agent-shard-2